spring.application.name=SwipeJamBackend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/swipejam
spring.datasource.username=costingrasu
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# "update" will automatically create the tables based on our Entities during development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Temporary Spring Security Default User (so it doesn't randomly generate a password on startup)
spring.security.user.name=admin
spring.security.user.password=admin
